// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: whishlist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item_ItemPriority int32

const (
	Item_LOW  Item_ItemPriority = 0
	Item_MID  Item_ItemPriority = 50
	Item_HIGH Item_ItemPriority = 100
)

// Enum value maps for Item_ItemPriority.
var (
	Item_ItemPriority_name = map[int32]string{
		0:   "LOW",
		50:  "MID",
		100: "HIGH",
	}
	Item_ItemPriority_value = map[string]int32{
		"LOW":  0,
		"MID":  50,
		"HIGH": 100,
	}
)

func (x Item_ItemPriority) Enum() *Item_ItemPriority {
	p := new(Item_ItemPriority)
	*p = x
	return p
}

func (x Item_ItemPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_ItemPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_whishlist_proto_enumTypes[0].Descriptor()
}

func (Item_ItemPriority) Type() protoreflect.EnumType {
	return &file_whishlist_proto_enumTypes[0]
}

func (x Item_ItemPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_ItemPriority.Descriptor instead.
func (Item_ItemPriority) EnumDescriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{0, 0}
}

type Item_ItemStatus int32

const (
	Item_INACTIVE Item_ItemStatus = 0
	Item_ACTIVE   Item_ItemStatus = 1
)

// Enum value maps for Item_ItemStatus.
var (
	Item_ItemStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	Item_ItemStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x Item_ItemStatus) Enum() *Item_ItemStatus {
	p := new(Item_ItemStatus)
	*p = x
	return p
}

func (x Item_ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_whishlist_proto_enumTypes[1].Descriptor()
}

func (Item_ItemStatus) Type() protoreflect.EnumType {
	return &file_whishlist_proto_enumTypes[1]
}

func (x Item_ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_ItemStatus.Descriptor instead.
func (Item_ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{0, 1}
}

type Wishlist_WishlistStatus int32

const (
	Wishlist_INACTIVE Wishlist_WishlistStatus = 0
	Wishlist_ACTIVE   Wishlist_WishlistStatus = 1
)

// Enum value maps for Wishlist_WishlistStatus.
var (
	Wishlist_WishlistStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	Wishlist_WishlistStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x Wishlist_WishlistStatus) Enum() *Wishlist_WishlistStatus {
	p := new(Wishlist_WishlistStatus)
	*p = x
	return p
}

func (x Wishlist_WishlistStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Wishlist_WishlistStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_whishlist_proto_enumTypes[2].Descriptor()
}

func (Wishlist_WishlistStatus) Type() protoreflect.EnumType {
	return &file_whishlist_proto_enumTypes[2]
}

func (x Wishlist_WishlistStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Wishlist_WishlistStatus.Descriptor instead.
func (Wishlist_WishlistStatus) EnumDescriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{1, 0}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WishlistId string            `protobuf:"bytes,2,opt,name=wishlistId,proto3" json:"wishlistId,omitempty"`
	Name       string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Link       string            `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Price      float64           `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Priority   Item_ItemPriority `protobuf:"varint,6,opt,name=priority,proto3,enum=wishlist.Item_ItemPriority" json:"priority,omitempty"`
	Status     Item_ItemStatus   `protobuf:"varint,7,opt,name=status,proto3,enum=wishlist.Item_ItemStatus" json:"status,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetPriority() Item_ItemPriority {
	if x != nil {
		return x.Priority
	}
	return Item_LOW
}

func (x *Item) GetStatus() Item_ItemStatus {
	if x != nil {
		return x.Status
	}
	return Item_INACTIVE
}

type Wishlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status Wishlist_WishlistStatus `protobuf:"varint,3,opt,name=status,proto3,enum=wishlist.Wishlist_WishlistStatus" json:"status,omitempty"`
}

func (x *Wishlist) Reset() {
	*x = Wishlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wishlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wishlist) ProtoMessage() {}

func (x *Wishlist) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wishlist.ProtoReflect.Descriptor instead.
func (*Wishlist) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{1}
}

func (x *Wishlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wishlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wishlist) GetStatus() Wishlist_WishlistStatus {
	if x != nil {
		return x.Status
	}
	return Wishlist_INACTIVE
}

// Requests and responses
// Method used to create a wishlist
type CreateWishlistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wishlist *Wishlist `protobuf:"bytes,1,opt,name=wishlist,proto3" json:"wishlist,omitempty"`
}

func (x *CreateWishlistReq) Reset() {
	*x = CreateWishlistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishlistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishlistReq) ProtoMessage() {}

func (x *CreateWishlistReq) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishlistReq.ProtoReflect.Descriptor instead.
func (*CreateWishlistReq) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWishlistReq) GetWishlist() *Wishlist {
	if x != nil {
		return x.Wishlist
	}
	return nil
}

type CreateWishlistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishlistId string `protobuf:"bytes,1,opt,name=wishlistId,proto3" json:"wishlistId,omitempty"`
}

func (x *CreateWishlistRes) Reset() {
	*x = CreateWishlistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishlistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishlistRes) ProtoMessage() {}

func (x *CreateWishlistRes) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishlistRes.ProtoReflect.Descriptor instead.
func (*CreateWishlistRes) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWishlistRes) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

// Method used to create an item
type AddItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *AddItemRes) Reset() {
	*x = AddItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRes) ProtoMessage() {}

func (x *AddItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRes.ProtoReflect.Descriptor instead.
func (*AddItemRes) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemRes) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// Method used to list the items of a list
type ListWishlistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishlistId string `protobuf:"bytes,1,opt,name=wishlistId,proto3" json:"wishlistId,omitempty"`
}

func (x *ListWishlistReq) Reset() {
	*x = ListWishlistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishlistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishlistReq) ProtoMessage() {}

func (x *ListWishlistReq) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishlistReq.ProtoReflect.Descriptor instead.
func (*ListWishlistReq) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{6}
}

func (x *ListWishlistReq) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

type ListWishlistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListWishlistRes) Reset() {
	*x = ListWishlistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whishlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishlistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishlistRes) ProtoMessage() {}

func (x *ListWishlistRes) ProtoReflect() protoreflect.Message {
	mi := &file_whishlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishlistRes.ProtoReflect.Descriptor instead.
func (*ListWishlistRes) Descriptor() ([]byte, []int) {
	return file_whishlist_proto_rawDescGZIP(), []int{7}
}

func (x *ListWishlistRes) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_whishlist_proto protoreflect.FileDescriptor

var file_whishlist_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x77, 0x68, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xb4, 0x02, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x77, 0x69,
	0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a,
	0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x07,
	0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x49, 0x44, 0x10, 0x32,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x64, 0x22, 0x26, 0x0a, 0x0a, 0x49, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x01, 0x22, 0x95, 0x01, 0x0a, 0x08, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x57,
	0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a,
	0x0a, 0x0e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x22, 0x43, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x2e, 0x0a, 0x08, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x69, 0x73,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x33, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x24, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22,
	0x37, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xe2, 0x01, 0x0a, 0x0f, 0x57, 0x69, 0x73,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1b,
	0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x69,
	0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x77, 0x69,
	0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x72, 0x69, 0x63,
	0x6b, 0x79, 0x70, 0x65, 0x2f, 0x47, 0x6f, 0x67, 0x52, 0x50, 0x43, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_whishlist_proto_rawDescOnce sync.Once
	file_whishlist_proto_rawDescData = file_whishlist_proto_rawDesc
)

func file_whishlist_proto_rawDescGZIP() []byte {
	file_whishlist_proto_rawDescOnce.Do(func() {
		file_whishlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_whishlist_proto_rawDescData)
	})
	return file_whishlist_proto_rawDescData
}

var file_whishlist_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_whishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_whishlist_proto_goTypes = []interface{}{
	(Item_ItemPriority)(0),       // 0: wishlist.Item.ItemPriority
	(Item_ItemStatus)(0),         // 1: wishlist.Item.ItemStatus
	(Wishlist_WishlistStatus)(0), // 2: wishlist.Wishlist.WishlistStatus
	(*Item)(nil),                 // 3: wishlist.Item
	(*Wishlist)(nil),             // 4: wishlist.Wishlist
	(*CreateWishlistReq)(nil),    // 5: wishlist.CreateWishlistReq
	(*CreateWishlistRes)(nil),    // 6: wishlist.CreateWishlistRes
	(*AddItemReq)(nil),           // 7: wishlist.AddItemReq
	(*AddItemRes)(nil),           // 8: wishlist.AddItemRes
	(*ListWishlistReq)(nil),      // 9: wishlist.ListWishlistReq
	(*ListWishlistRes)(nil),      // 10: wishlist.ListWishlistRes
}
var file_whishlist_proto_depIdxs = []int32{
	0,  // 0: wishlist.Item.priority:type_name -> wishlist.Item.ItemPriority
	1,  // 1: wishlist.Item.status:type_name -> wishlist.Item.ItemStatus
	2,  // 2: wishlist.Wishlist.status:type_name -> wishlist.Wishlist.WishlistStatus
	4,  // 3: wishlist.CreateWishlistReq.wishlist:type_name -> wishlist.Wishlist
	3,  // 4: wishlist.AddItemReq.item:type_name -> wishlist.Item
	3,  // 5: wishlist.ListWishlistRes.items:type_name -> wishlist.Item
	5,  // 6: wishlist.WishlistService.CreateWishlist:input_type -> wishlist.CreateWishlistReq
	7,  // 7: wishlist.WishlistService.AddItemWishlist:input_type -> wishlist.AddItemReq
	9,  // 8: wishlist.WishlistService.ListWishlist:input_type -> wishlist.ListWishlistReq
	6,  // 9: wishlist.WishlistService.CreateWishlist:output_type -> wishlist.CreateWishlistRes
	8,  // 10: wishlist.WishlistService.AddItemWishlist:output_type -> wishlist.AddItemRes
	10, // 11: wishlist.WishlistService.ListWishlist:output_type -> wishlist.ListWishlistRes
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_whishlist_proto_init() }
func file_whishlist_proto_init() {
	if File_whishlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_whishlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wishlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishlistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishlistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWishlistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_whishlist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWishlistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_whishlist_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whishlist_proto_goTypes,
		DependencyIndexes: file_whishlist_proto_depIdxs,
		EnumInfos:         file_whishlist_proto_enumTypes,
		MessageInfos:      file_whishlist_proto_msgTypes,
	}.Build()
	File_whishlist_proto = out.File
	file_whishlist_proto_rawDesc = nil
	file_whishlist_proto_goTypes = nil
	file_whishlist_proto_depIdxs = nil
}
